language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: m8iDOQtVn3ZgH7SzeLmaa8zcRAVoo1QLcDsgeJnTYMkHI8br7r+Iq4nuL88Mh3gv/XI7mIz6V43APP2HKVH6um99+V8rXqtKPj/8JN15ZBM7qQv07IYEG6P8C1SxIQU97nC8389GJ5Boyd3/H0DydmmsMU20rslF4CJJbNPVFYeVxiTfaN67A1JsgyKesiANGqLFfDqZorGz7KIboHnD+PHTp7Xy7c9kNLI+TbCbDlGKGcIhs04Uu5l1JpAu97Bn0cAVNKctq8lmPBRqtfXjQpMMg81BV8P0IG4H0JhnMJ6fU8m42G9Sq2ewm0neSoi79WCXqHsWyHcgTB4UdvoU/2Cj+uPwYb4urZ+tpJTlPZUGwhK9/6rz4qM8yg8YYcplMmkNGijPEs6pe9G+rB9OZ7/DVWAC5s+L7t7ErkHjNnphctjN9/uJQqCz1Qd6LggV4rXknQq3t+z6DE2NK9OHnFeDFHYjqhkEsgnC1Kzg/nN636gC5H9PFoBK/rC5b8mJEIo0n/VYK79JclLytWmxYPGGj2xqHBz16sLpck1QiSqmsIxnGbiSECPP+SKk5rryHVZh9DwzIKVf8zYposnM4bSFw7iMTKw+p1wCsDHmQNKm1el7YoLPcEYCk4erPUNnSoI0FAxOsc+0INmBJhWEXYfe+KofdwCMsZfPw2vNsN4=
  app: directorsnotesapp
  on:
    repo: KatelinDeSerano/directorsNotesApp
